mi/urls.py
from django.urls import path
from mi.views import *

app_name='mi'

urlpatterns=[
    path('rohit/',rohit,name='rohit'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import mi
from rcb.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('virat/',virat,name='virat'),
    path('mi/',include('mi.urls')),
]

mi/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

mi/views.py
from django.shortcuts import render

# Create your views here.

def rohit(request):
    return render(request,'rohit.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.

def virat(request):
    return render(request,'virat.html')

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>rohit html page</h1>
        <h1>this belongs to MI</h1>
        <a href="{% url 'virat' %}">Navigate to virat</a>
    </center>
    
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>virat html page</h1>
        <h1>this belongs to RCB</h1>
        <a href="{% url 'mi:rohit' %}">Go to Rohit page</a>
    </center>
    
</body>
</html>